server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002 #去掉显示本机主机名
    prefer-ip-address: true  #显示注册的ip

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    #url: jdbc:mysql://192.168.24.28:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: system

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.les.springcloud.entities #entity别名类所在包
 
 
