server:
   port: 80
   servlet:
     context-path: /consumer-fegin-hystrix

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

#设置超时时间：openfegion默认1秒，默认集成ribbon
#ribbon:
#  ConnectTimeout: 5000 #连接超时  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout:  6000 #操作超时 >=连接超时     指的是建立连接后从服务器读取到可用资源所用的时间

feign:
  hystrix:
    enabled: true #消费者端如果处理自身的容错就开启。开启方式与生产端@EnableCircuitBreaker不一样。

